name: workflow_dispatch sample 1

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish to Github Packages Registry
        run: echo "Hello!"
