name: workflow_dispatch sample 1

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      # チェックアウト
      - uses: actions/checkout@v3
      - name: Build and Publish to Github Container Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        run: ls -al
        with:
          name: y-p-e/DonutsSite/donuts-site-image
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: prod.Dockerfile
          tags: latest
